### PR TITLE
Support Custom protocol

### PR DESCRIPTION
**Pull request by mouryaravi**
Support Custom protocol option (HTTP/HTTPS) defaults to `HTTPS`.

### CODE REVIEW

**Comment by joelittlejohn** [comment]
Hi Ravi. I'm interested to know why you need this feature. Do you work in environment that only allows http?

**Comment by mouryaravi** [comment]
To explain the intent for this PR - 
We have a scenario : Our app needs to call dynamo with HTTP so that envoy (sidecar) interprets the call and does the HTTPS connection

**Comment by mouryaravi** [comment]
> Hi Ravi. I'm interested to know why you need this feature. Do you work in environment that only allows http?

I have just added comment. Hope that explains.

**Comment by mouryaravi** [comment]
@joelittlejohn would it be possible to create a new release / tag when this PR is merged? We need some changes from master branch which are not there in `1.11.1` tag.

**Comment by mouryaravi** [comment]
@joelittlejohn can you suggest if you can review and merge this PR or is there any other person that I need to follow up with?
thanks!

**Comment by joelittlejohn** [comment]
@mouryaravi Are you able to add a line to this test please:

https://github.com/Taoensso/faraday/blob/master/test/taoensso/faraday/tests/main.clj#L71

Once that's done I'm happy to merge and release 1.11.2

**Comment by mouryaravi** [comment]
I have added the tests. Thanks for the reminder @joelittlejohn

**Comment by joelittlejohn** [comment]
@mouryaravi This is released now: `[com.taoensso/faraday "1.11.2"]`

**Pull request closed without merging**
