### PR TITLE
Allow string table names in query and scan

### PR DESCRIPTION
**Pull request by JonathanHarford**
Noted in #159.

### CODE REVIEW

**Comment by tobias** [comment]
Hi @joelittlejohn! Would it be possible to cut a new release with this change? It would be helpful to us.

**Comment by joelittlejohn** [comment]
@tobias done, 1.11.3 is live :tada:

**Comment by joelittlejohn** [comment]
@tobias You may prefer to use 1.11.4 instead. We were hit by https://github.com/technomancy/leiningen/issues/2721 so the previous release includes some dev dependencies that are only used to run tests.

**Comment by tobias** [comment]
Thanks again @joelittlejohn, I updated our dependency.

**Pull request merged**
